- currencies: usd,eur   # List of fiat currencies for creating deposits.
  traders:    25        # Number of members who will trade.
  threads:    50        # Number of simultaneous threads which will publish messages to RabbitMQ.
  orders:
    #
    # Generic config.
    injector:   dummy   # Order injector name.
    number:     1000    # Number of orders to be created and published to RabbitMQ (at least 10000).
    markets:    usdeur  # Markets for performing trading.
    #
    # Dummy injector specific config.
    min_volume: 0.1     # Order min volume (default 0.1).
    max_volume: 1.0     # Order max volume (default 1.0).
    min_price:  0.5     # Order min price (default 0.5).
    max_price:  2.0     # Order max price (default 2.0).

- currencies: usd,eur   # List of fiat currencies for creating deposits.
  traders:    25        # Number of members who will trade.
  threads:    50        # Number of simultaneous threads which will publish messages to RabbitMQ.
  orders:
    #
    # Generic config.
    injector:       bitfinex  # Order injector name.
    number:         1000      # Number of orders to be created and published to RabbitMQ (at least 10000).
    markets:        usdeur    # Markets for performing trading.
    #
    # Bitfinex injector specific config.
    data_load_path: config/bench/data/neo-usd-data.csv # Path to bitfinex order history file.
